# Generated by Django 3.2.20 on 2023-08-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='colors',
            new_name='product_color',
        ),
    ]
