# Generated by Django 3.2.20 on 2023-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_colours',
            field=models.BooleanField(blank=True, max_length=200, null=True),
        ),
    ]
