# Generated by Django 4.2.3 on 2023-07-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
